reddit_topic_warehouse:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: virtual-flux-455815-k4
      dataset: dbt_euw4
      threads: 2
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: europe-west4
