name: Reddit Topic Warehouse Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: dbt/models/reddit_topic_warehouse/
      GCP_SA_KEY: "${{ secrets.GCP_SA_KEY }}"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug repo structure
        run: |
          pwd
          ls -la
          echo "---- dbt folder ----"
          ls -la dbt || true
          echo "---- dbt/models ----"
          ls -la dbt/models || true
          echo "---- find dbt_project.yml ----"
          find . -maxdepth 6 -name dbt_project.yml -print
          echo "---- find dbt_project.yml ----"
          find . -maxdepth 6 -name dbt_project.yml -print

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: dbt deps
        working-directory: dbt/models/reddit_topic_warehouse/
        run: dbt deps

      - name: dbt run (staging + silver + gold)
        working-directory: dbt/models/reddit_topic_warehouse/
        run: dbt run --select staging silver gold

      - name: dbt test (staging + silver + gold)
        working-directory: dbt/models/reddit_topic_warehouse/
        run: dbt test --select staging silver gold
